-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 01:14:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rol` (
  `idRol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoUsuario` (
  `idEstado` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `codigoPucp` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correoPucp` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `condicion` VARCHAR(45) NOT NULL,
  `Rol_idRol` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`codigoPucp`),
  INDEX `fk_Participante_Rol1_idx` (`Rol_idRol` ASC) ,
  INDEX `fk_Participante_Estado1_idx` (`Estado_idEstado` ASC) ,
  CONSTRAINT `fk_Participante_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `mydb`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participante_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `mydb`.`EstadoUsuario` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Donacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Donacion` (
  `idDonacion` INT NOT NULL AUTO_INCREMENT,
  `monto` VARCHAR(45) NOT NULL,
  `contribuyente_codigoPucp` INT NOT NULL,
  PRIMARY KEY (`idDonacion`),
  INDEX `fk_Donacion_Participante1_idx` (`contribuyente_codigoPucp` ASC) ,
  CONSTRAINT `fk_Donacion_Participante1`
    FOREIGN KEY (`contribuyente_codigoPucp`)
    REFERENCES `mydb`.`Usuarios` (`codigoPucp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Actividad` (
  `idActividad` INT NOT NULL AUTO_INCREMENT,
  `nombreActividad` VARCHAR(45) NULL,
  `delegado_codigoPucp` INT NOT NULL,
  PRIMARY KEY (`idActividad`),
  INDEX `fk_Actividad_Participante1_idx` (`delegado_codigoPucp` ASC) ,
  CONSTRAINT `fk_Actividad_Participante1`
    FOREIGN KEY (`delegado_codigoPucp`)
    REFERENCES `mydb`.`Usuarios` (`codigoPucp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(45) NULL,
  `Actividad_idActividad` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Actividad1_idx` (`Actividad_idActividad` ASC) ,
  CONSTRAINT `fk_Evento_Actividad1`
    FOREIGN KEY (`Actividad_idActividad`)
    REFERENCES `mydb`.`Actividad` (`idActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstadoEvento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EstadoEvento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EstadoEvento` (
  `idEstadoEvento` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Participante_a_Evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Participante_a_Evento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Participante_a_Evento` (
  `Participante_codigoPucp` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `EstadoEvento_idEstadoEvento` INT NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`Participante_codigoPucp`, `Evento_idEvento`),
  INDEX `fk_Participante_has_Evento_Evento1_idx` (`Evento_idEvento` ASC) ,
  INDEX `fk_Participante_has_Evento_Participante1_idx` (`Participante_codigoPucp` ASC) ,
  INDEX `fk_Participante_a_Evento_EstadoEvento1_idx` (`EstadoEvento_idEstadoEvento` ASC) ,
  CONSTRAINT `fk_Participante_has_Evento_Participante1`
    FOREIGN KEY (`Participante_codigoPucp`)
    REFERENCES `mydb`.`Usuarios` (`codigoPucp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participante_has_Evento_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participante_a_Evento_EstadoEvento1`
    FOREIGN KEY (`EstadoEvento_idEstadoEvento`)
    REFERENCES `mydb`.`EstadoEvento` (`idEstadoEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
